// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"time"
)

type Url struct {
	ID            int64
	ShortID       string
	ShortUrl      string
	LongUrl       string
	RedirectCount int32
	CreatedAt     time.Time
}
